
-- JOBS definition
CREATE TABLE JOBS 
   (JOB_ID VARCHAR(10), 
	JOB_TITLE VARCHAR(35) NOT NULL, 
	MIN_SALARY NUMERIC(6,0), 
	MAX_SALARY NUMERIC(6,0), 
	 CONSTRAINT JOB_ID_PK PRIMARY KEY (JOB_ID)
   );



-- JOBS_SNAPSHOT definition
CREATE TABLE JOBS_SNAPSHOT 
   (JOB_ID VARCHAR(10), 
	JOB_TITLE VARCHAR(35) NOT NULL, 
	MIN_SALARY NUMERIC(6,0), 
	MAX_SALARY NUMERIC(6,0)
   );


  
-- REGIONS definition
CREATE TABLE REGIONS 
   (REGION_ID NUMERIC CONSTRAINT REGION_ID_NN NOT NULL, 
	REGION_NAME VARCHAR(25), 
	 CONSTRAINT REG_ID_PK PRIMARY KEY (REGION_ID)
   );



-- COUNTRIES definition
CREATE TABLE COUNTRIES 
   (COUNTRY_ID CHAR(2) CONSTRAINT COUNTRY_ID_NN NOT NULL, 
	COUNTRY_NAME VARCHAR(40), 
	REGION_ID NUMERIC, 
	DATE_LAST_UPDATED DATETIME DEFAULT GETDATE(), 
	 CONSTRAINT COUNTRY_C_ID_PK PRIMARY KEY (COUNTRY_ID), 
	 CONSTRAINT COUNTR_REG_FK FOREIGN KEY (REGION_ID) REFERENCES REGIONS (REGION_ID)
   );




-- LOCATIONS definition
CREATE TABLE LOCATIONS 
   (LOCATION_ID NUMERIC(4,0), 
	STREET_ADDRESS VARCHAR(40), 
	POSTAL_CODE VARCHAR(12), 
	CITY VARCHAR(30) CONSTRAINT LOC_CITY_NN NOT NULL, 
	STATE_PROVINCE VARCHAR(25), 
	COUNTRY_ID CHAR(2), 
	 CONSTRAINT LOC_ID_PK PRIMARY KEY (LOCATION_ID), 
	 CONSTRAINT LOC_C_ID_FK FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES (COUNTRY_ID)
   );

CREATE INDEX LOC_CITY_IX ON LOCATIONS (CITY);
CREATE INDEX LOC_STATE_PROVINCE_IX ON LOCATIONS (STATE_PROVINCE);
CREATE INDEX LOC_COUNTRY_IX ON LOCATIONS (COUNTRY_ID);



-- DEPARTMENTS definition
CREATE TABLE DEPARTMENTS 
   (DEPARTMENT_ID NUMERIC(4,0), 
	DEPARTMENT_NAME VARCHAR(30) CONSTRAINT DEPT_NAME_NN NOT NULL, 
	MANAGER_ID NUMERIC(6,0), 
	LOCATION_ID NUMERIC(4,0), 
	URL VARCHAR(255), 
	 CONSTRAINT DEPT_ID_PK PRIMARY KEY (DEPARTMENT_ID), 
	 CONSTRAINT DEPT_LOC_FK FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS (LOCATION_ID) 
   ) ;

CREATE INDEX DEPT_LOCATION_IX ON DEPARTMENTS (LOCATION_ID);



-- JOB_HISTORY definition
CREATE TABLE JOB_HISTORY 
   (EMPLOYEE_ID NUMERIC(6,0) CONSTRAINT JHIST_EMPLOYEE_NN NOT NULL, 
	START_DATE DATETIME CONSTRAINT JHIST_START_DATE_NN NOT NULL, 
	END_DATE DATETIME CONSTRAINT JHIST_END_DATE_NN NOT NULL, 
	JOB_ID VARCHAR(10) CONSTRAINT JHIST_JOB_NN NOT NULL, 
	DEPARTMENT_ID NUMERIC(4,0), 
	 CONSTRAINT JHIST_DATE_INTERVAL CHECK (end_date > start_date), 
	 CONSTRAINT JHIST_EMP_ID_ST_DATE_PK PRIMARY KEY (EMPLOYEE_ID, START_DATE), 
	 CONSTRAINT JHIST_JOB_FK FOREIGN KEY (JOB_ID) REFERENCES JOBS (JOB_ID), 
	 CONSTRAINT JHIST_DEPT_FK FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS (DEPARTMENT_ID)
   ) ;

CREATE INDEX JHIST_JOB_IX ON JOB_HISTORY (JOB_ID);
CREATE INDEX JHIST_EMPLOYEE_IX ON JOB_HISTORY (EMPLOYEE_ID);
CREATE INDEX JHIST_DEPARTMENT_IX ON JOB_HISTORY (DEPARTMENT_ID);




-- EMPLOYEES definition
CREATE TABLE EMPLOYEES 
   (EMPLOYEE_ID NUMERIC(6,0), 
	FIRST_NAME VARCHAR(20), 
	LAST_NAME VARCHAR(25) CONSTRAINT EMP_LAST_NAME_NN NOT NULL, 
	EMAIL VARCHAR(25) CONSTRAINT EMP_EMAIL_NN NOT NULL, 
	PHONE_NUMBER VARCHAR(20), 
	HIRE_DATE DATETIME CONSTRAINT EMP_HIRE_DATE_NN NOT NULL, 
	JOB_ID VARCHAR(10) CONSTRAINT EMP_JOB_NN NOT NULL, 
	SALARY NUMERIC(8,2), 
	COMMISSION_PCT NUMERIC(2,2), 
	MANAGER_ID NUMERIC(6,0), 
	DEPARTMENT_ID NUMERIC(4,0), 
	SOME_DATE_FMT1 VARCHAR(50), 
	SOME_DATE_FMT2 VARCHAR(50), 
	SOME_DATE_FMT3 VARCHAR(50), 
	SOME_DATE_FMT4 VARCHAR(50), 
	FAKE_SSN VARCHAR(11), 
	ZIP5 VARCHAR(5), 
	ZIP5OR9 VARCHAR(10), 
	ZIP9 VARCHAR(10), 
	EMAIL_ADDRESS VARCHAR(100), 
	 CONSTRAINT EMP_SALARY_MIN CHECK (salary > 0), 
	 CONSTRAINT EMP_EMAIL_UK UNIQUE (EMAIL), 
	 CONSTRAINT EMP_EMP_ID_PK PRIMARY KEY (EMPLOYEE_ID), 
	 CONSTRAINT EMP_DEPT_FK FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS (DEPARTMENT_ID), 
	 CONSTRAINT EMP_JOB_FK FOREIGN KEY (JOB_ID) REFERENCES JOBS (JOB_ID), 
	 CONSTRAINT EMP_MANAGER_FK FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES (EMPLOYEE_ID)
   ) ;

CREATE INDEX EMP_DEPARTMENT_IX ON EMPLOYEES (DEPARTMENT_ID);
CREATE INDEX EMP_JOB_IX ON EMPLOYEES (JOB_ID);
CREATE INDEX EMP_MANAGER_IX ON EMPLOYEES (MANAGER_ID);
CREATE INDEX EMP_NAME_IX ON EMPLOYEES (LAST_NAME, FIRST_NAME);





