DROP TABLE IF EXISTS categories CASCADE;

DROP TABLE IF EXISTS customer_customer_demo CASCADE;

DROP TABLE IF EXISTS customer_demographics CASCADE;

DROP TABLE IF EXISTS customers CASCADE;

DROP TABLE IF EXISTS employees CASCADE;

DROP TABLE IF EXISTS employee_territories CASCADE;

DROP TABLE IF EXISTS order_details CASCADE;

DROP TABLE IF EXISTS orders CASCADE;

DROP TABLE IF EXISTS products CASCADE;

DROP TABLE IF EXISTS region CASCADE;

DROP TABLE IF EXISTS shippers CASCADE;

DROP TABLE IF EXISTS suppliers CASCADE;

DROP TABLE IF EXISTS territories CASCADE;

DROP TABLE IF EXISTS us_states CASCADE;

